### PR TITLE
fix(RootSchema.Unmarshal): permit opaque properties

### LINKED ISSUE #44: Schema parsing - Permit opaque key-values in Property schema
Currently, this schema is valid according to https://www.jsonschemavalidator.net/

```
{
    "$id": "https://www.github.com/schemas/robfig",
    "properties": {
        "name": {
            "type": "string",
            "opaque": "something"
        }
    }
}
```

But it can be unmarshaled by this library, receiving this error:
```
error unmarshaling properties from json: error unmarshaling opaque from json: json: cannot unmarshal string into Go value of type jsonschema._schema
```

That is due to this code, which assumes any extra key must be a Definition:
```
	for prop, rawmsg := range valprops {
		var val Validator
		if mk, ok := DefaultValidators[prop]; ok {
			val = mk()
		} else {
			switch prop {
			// skip any already-parsed props
			case "$schema", "$id", "title", "description", "default", "examples", "readOnly", "writeOnly", "$comment", "$ref", "definitions", "format":
				continue
			default:
				// assume non-specified props are "extra definitions"
				if sch.extraDefinitions == nil {
					sch.extraDefinitions = Definitions{}
				}
				s := new(Schema)
				if err := json.Unmarshal(rawmsg, s); err != nil {
					return fmt.Errorf("error unmarshaling %s from json: %s", prop, err.Error())
				}
				sch.extraDefinitions[prop] = s
				continue
			}
		}
		if err := json.Unmarshal(rawmsg, val); err != nil {
			return fmt.Errorf("error unmarshaling %s from json: %s", prop, err.Error())
		}
		sch.Validators[prop] = val
	}
```

The relevant portion of the spec says that definitions must be collected under a "definitions" key
https://json-schema.org/latest/json-schema-validation.html#rfc.section.9

So, it seems like the the code should be updated to pull out just the "definitions" key, and then apply the "parse the values of each key under that as a Schema". 

If you agree, I will add unit tests for this case and make a pull request.

### PR DESCRIPTION
**Pull request by robfig**
add a unit test to verify the behavior

fixes #44

### CODE REVIEW

**Comment by robfig** [comment]
Although, it seems like it's worth adding support for the "definitions" key and returning errors for anything under that which doesn't unmarshal as a schema..

**Comment by robfig** [comment]
Yeah.. not sure this is a good idea as-is. Errors parsing children of "properties" and "items" would no longer be reported.

**Comment by NikolaLohinski** [comment]
Hi there and thanks for this lib, we really appreciate it !

This feature is a big plus for us, since we need to overload our standard compliant schemas with custom fields. Is there at least a way to set a flag in the rootSchema to enable a kind of "loose" unmarshalling to trigger this behaviour ? The "strict" unmarshalling could still be the default one.

**Comment by Arqu** [comment]
Closing this as stale as we moved to a newer draft and re-implemented most of jsonschema.

**Pull request closed without merging**
