### PR TITLE
Use a local keyword registry to make validate thread-safe

### PR DESCRIPTION
**Pull request by carolynvs**
This makes validating a schema thread-safe. I was focused on fixing that call path specifically, and not addressing thread-safety throughout the entire code base, so there is may be more global variables being used elsewhere. This PR introduces a a struct to represent a keyword registry, and loading of the registry and validation occurs in instances of a keyword registry, avoiding the use of global package variables. 

This is the patch that we have been using for https://github.com/getporter/porter for 6+ months to be able to validate a schema in a thread-safe manner when registering custom validators. 

I was mostly interested in getting this to work without making any backwards incompatible changes to this library's existing API. For example, I kept the package level functions that manipulate package variables, such as `RegisterKeyword`, which requires the use of locks. If you are okay with making a breaking change, and removing global state, that would simplify the patch quite a bit.

This is a fix for #80 , but is limited to validation. There are probably more spots that would need to be refactored as well.

### CODE REVIEW

**Comment by Arqu** [comment]
Again, very appreciated. This will take a bit more time to review as I have to be more thorough with it and do some testing, but at a glance looks like a step in the right direction.

**Comment by carolynvs** [comment]
@Arqu Just checking if you've had a chance to look at this and had any feedback?

**Comment by Arqu** [comment]
Sorry, been pretty booked for the past while. I'll aim to have a go at it within the next 10 days.

**Review by Arqu — CHANGES_REQUESTED** [review]
Thank you for the patience, this is exceptional and brings us much closer to being fully thread safe. Before merging, if you could just address the golint issues 
```
draft2019_09_keywords.go:14:1: exported method KeywordRegistry.DefaultIfEmpty should have comment or be unexported
keyword.go:31:6: exported type KeywordRegistry should have comment or be unexported
keyword.go:55:1: exported method KeywordRegistry.Copy should have comment or be unexported
```
And I'm happy to merge as is.

**Comment by carolynvs** [comment]
Oh great! I'm excited to not have to have a fork of golint anymore! 🎉 I just pushed a fix for the golint errors.

**Review by Arqu — APPROVED** [review]
Thank you soo much for the work here, seems like this will help a lot of folks out!

**Pull request merged**
